### ISSUE TITLE
Créer un menu

### ISSUE THREAD

**Issue by 1v7w55** [1v7w55/wildland-fire-emulation#2]
Créer une interface à l'utilisateur où il peut choisir:
- Remplissage aléatoire de la forêt
- Remplissage manuel

du type:
Choisissez le mode de générations: 
1- Remplissage aléatoire de la forêt
2- Remplissage manuel
Quel mode avez-vous choisi ?
scanf()...

Attention à bien prendre en compte l'input utilisateur est bien 1 ou 2, rien d'autres

**Comment by SachaGitH** [comment]
Je m'en occupe
