### ISSUE TITLE
Affichage des anciennes itérations

### ISSUE THREAD

**Issue by 1v7w55** [1v7w55/wildland-fire-emulation#8]
Afficher les dernières itérations que l'utilisateur a eu pour son cas.
**Attention, il faut faire le #7 avant.**
Permettre de "revoir" les actions effectuer, **le feu n'est toujours pas pris en compte.**
Compte le nombre d'étapes:
Permettre à l'utilisateur de revoir toutes les étapes ou seulement une:
Voulez-vous revoir votre partie ?
1 - Oui
2 - Non

_Si oui,_
Quel moment ?
1 - Je veux tout revoir
2 - Seulement une partie

_Si 1,_
Afficher toutes les étapes

_Si 2,_
Quelle partie ?
0, Partie 0
1, Partie 1
...
Indiquer le numéro de partie ?

_Afficher la partie choisie_

Une fois afficher:
Voulez-vous revoir un autre moment ?
1 - Oui
2 - Non (Quitter)

_Si oui, 
Remettre le menu précédent._
_Si oui,_
Quel moment ?
1 - Je veux tout revoir
2 - Seulement une partie

**Comment by SachaGitH** [comment]
Possible de gérer avec un fichier texte ou une pile :)
